### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by mikan0w0** [mikan0w0/furima-29279#10]
#URL
https://furima-29279.herokuapp.com/

#Basic認証のIDとパスワード
admin・2222

#出品者用のメールアドレスとパスワード
email: mikan@mikan
password: mi12345

#購入者用のメールアドレスとパスワード
email: meron@meron
password: me12345

購入用カードの番号・期限・セキュリティコード
カード番号: 4242424242424242
有効年月: 3/23
cvc: 123

よろしくお願いします！

**Comment by ryszw** [comment]
烏山さん、ご提出ありがとうございます！
挙動確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！

**※確認したのは必須機能のみで追加実装した機能については確認していません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるかご自身で再度確認をお願いいたします。**

**Comment by mikan0w0** [comment]
レビューいただきありがとうございました！！
